name: e_commerce_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.6.1
  font_awesome_flutter: ^10.4.0
  go_router: ^6.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Black.otf
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-Medium.otf
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-SemiBold.otf
